### PR TITLE
#1065 🐛 Fix using deprecated fargate resource quota

### LINKED ISSUE #1065: Update fargate quota check to use vCPU quota instead of task count
The Fargate resource quota check in okctl, `pkg/servicequota/fargatecheck.go`, must be updated to use quota code `L-3032A538` instead. 

[ref Slack-thread](https://oslokommune.slack.com/archives/C018EFCSC4W/p1666236126803609)

### PR DESCRIPTION
**Pull request by deifyed**
## Description

- Changes Fargate quota resource code in quota check from `L-790AF391`(number of pods) to `L-3032A538`(number of virtual
    CPU units)

## Motivation and Context

Closes #1065

## Verify the bug

1. Verify that the AWS account you are using has `0 applied quota` Fargate On-Demand resource count by going to 
    `AWS Console -> Service Quotas -> AWS Services -> AWS Fargate -> Fargate On-Demand resource count`
2. Try to create a new cluster (It's the cluster reconciler that has the check) with the latest okctl
3. Verify that the process fails due to lack of available Fargate pods

## Verify the fix

1. Try to create a new cluster with this PR on the same AWS account as above
2. Verify that the process does not fail due to lack of available Fargate Pods

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] I have updated the release notes (for the next release).

### CODE REVIEW

File: pkg/servicequota/fargatecheck.go [hunk 1]
```diff
@@ -29,15 +29,15 @@ func NewFargateCheck(required int, provider v1alpha1.CloudProvider) *FargateChec
 	}
 }
 
-// CheckAvailability determines if you have sufficient fargate pods
+// CheckAvailability determines if you have sufficient fargate vCPU resource count
```
Comment (yngvark) [inline pkg/servicequota/fargatecheck.go:32]:
```suggestion
// CheckAvailability determines if you have sufficient fargate vCPU resource count
// See: https://docs.aws.amazon.com/general/latest/gr/ecs-service.html#service-quotas-fargate
```

**Review by yngvark — APPROVED** [review]
+1 for fast fix
